name: final_year_project
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  google_fonts: ^4.0.3
  firebase_core: ^2.4.1
  flutter_native_splash: ^2.2.17
  get: ^4.6.5
  flutter_otp_text_field: ^1.1.1
  firebase_auth: ^4.2.5
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.4.0
  animated_notch_bottom_bar: ^0.0.1
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  liquid_swipe: ^3.0.0
  simple_shadow: ^0.3.1
  smooth_page_indicator: ^1.0.1
  carousel_slider: ^4.2.1
  file_picker: ^5.2.5
  flutter_neumorphic: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"

  image: assets/images/logo2.png

  android_12:
    image: assets/images/logo2.png
    icon_background_color: "#ffffff"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
